### ISSUE TITLE
pleading.tex

### ISSUE THREAD

**Issue by passamo9** [passamo9/LaTeX_EnglandWales_Templates#8]
Hi everyone,

Thank you so much for the speed at which changes are being done. It's absolutely incredible.

I've just started using LaTeX today, so please bear with me.

To use the pleading.tex, do I just copy and paste it in MacTex? I've tried that but it says `file ../engwales-plead not found`

Sorry for the stupid question.

**Comment by yjyao** [comment]
`../engwales-plead` is a file path, where `..` means "the parent directory (of your current directory)." so `../engwales-plead` expects a file called `engwales-plead.sty` at the directory above. if you only copied `pleading.tex`, then of course `../engwales-plead.sty` will not be there.

easiest way would be to always download the entire git repo. eventually you might want to learn to use git so it manages the sync for you. but learning git and LaTeX in a day sounds like a stretch.

**Comment by passamo9** [comment]
Yeah, I'm barely keep up with all the work that you're doing, as well as understanding how git works. But it's very exciting!

**Comment by Giebisch** [comment]
Has this been resolved with @bond7o6 's [comment](https://github.com/passamo9/LaTeX_EnglandWales_Templates/discussions/15#discussioncomment-367808) ?

**Comment by bond7o6** [comment]
This appears to be unrelated to that comment, but if some follow up on if either issues are still there would be good. @passamo9

**Comment by passamo9** [comment]
I think the wiki page is the basis for helping me sort this out. But this seems to have been also @Andonome in the Issue post about the Wiki about not being able to copy and paste.

Maybe we can discuss this point to make it clear how we will avoid this being an issue for new people (myself included).

Thanks!

**Comment by yjyao** [comment]
but have you been able to compile pleading.tex locally yet? if so then this should be closed; otherwise we need to help you figure out or else you won't get a hang of how the package will feel like as a user and that will prevent you from providing valuable feedback on the packages.

**Comment by passamo9** [comment]
Not yet.

What I have done so far:

Downloaded the Code
![Image 15-02-2021 at 22 05](https://user-images.githubusercontent.com/69139574/107992887-f55c8600-6fd9-11eb-8d6c-761ffaf03b17.jpg)

Where do I go from here?

**Comment by yjyao** [comment]
let's try this:
1. unzip
2. go to LaTeX_EnglandWales_Templates/examples/ 
3. open pleading.tex with your editor, MacTex is it?
4. compile the doc in MacTex as you do other .tex files.

**Comment by passamo9** [comment]
That's so so simple 🤦🏻‍♂️ staring me right in the face.

I really like the Opinion. It's perfect.

**Comment by passamo9** [comment]
The pleading.tex looks amazing!

We may have already discussed the solution, in which case, I am sorry for being so slow! But as is, it it missing the paragraph numbers.

Thank you again, this is really something else!

**Comment by yjyao** [comment]
> missing the paragraph numbers

it is. that example was created to showcase the `\maketitle` command (so far).

**Comment by yjyao** [comment]
if you managed to compile locally please close the thread as well. thanks!

**Comment by passamo9** [comment]
>it is. that example was created to showcase the \maketitle command (so far).

Ahh I see!

>if you managed to compile locally please close the thread as well. thanks!

Will do!
